package com.acme.architecture.testing.constant;

public final class ArchUnitPackageConstant {
	
	private ArchUnitPackageConstant() {
	}
	
	public static final String PACKAGE_INCLUDE = "..";
	
	//*** FINAL PACKAGE ***
	
	public static final String RESIDE_FINAL_PACKAGE_ENTITY_CLASS = "..entity";
	
	public static final String RESIDE_FINAL_PACKAGE_DTO_CLASS = "..dto";
	public static final String RESIDE_FINAL_PACKAGE_REQUEST_DTO_CLASS = "..request";
	public static final String RESIDE_FINAL_PACKAGE_RESPONSE_DTO_CLASS = "..response";
	public static final String RESIDE_FINAL_PACKAGE_QUERY_REQUEST_DTO_CLASS = "..query";
	
	public static final String RESIDE_FINAL_PACKAGE_REPOSITORY_CLASS = "..repository";
	public static final String RESIDE_FINAL_PACKAGE_REPOSITORY_IMPL_CLASS = RESIDE_FINAL_PACKAGE_REPOSITORY_CLASS + ".impl";
	public static final String RESIDE_FINAL_PACKAGE_SERVICE_CLASS = "..service";
	public static final String RESIDE_FINAL_PACKAGE_SERVICE_IMPL_CLASS = RESIDE_FINAL_PACKAGE_SERVICE_CLASS + ".impl";
	public static final String RESIDE_FINAL_PACKAGE_CONTROLLER_CLASS = "..controller";
	
	public static final String RESIDE_FINAL_PACKAGE_UTIL_CLASS = "..util";
	public static final String RESIDE_FINAL_PACKAGE_SUPPORT_CLASS = "..support";
	
	public static final String RESIDE_FINAL_PACKAGE_MAPPER_CLASS = "..mapper";
	public static final String RESIDE_FINAL_PACKAGE_MAPPER_IMPL_CLASS = RESIDE_FINAL_PACKAGE_MAPPER_CLASS + ".impl";
	
	public static final String RESIDE_FINAL_PACKAGE_DATA_FACTORY_CLASS = "..factory";
	public static final String RESIDE_FINAL_PACKAGE_DUMMY_CLASS = "..dummy";
	public static final String RESIDE_FINAL_PACKAGE_DUMMY_DATA_FACTORY_CLASS = "..factory.dummy";
	
	public static final String RESIDE_FINAL_PACKAGE_CONSTANT_CLASS = "..constant";
	public static final String RESIDE_FINAL_PACKAGE_EXCEPTION_CLASS = "..exception";
	public static final String RESIDE_FINAL_PACKAGE_ENUMERATION_CLASS = "..enumeration";
	public static final String RESIDE_FINAL_PACKAGE_ANNOTATION_CLASS = "..annotation";
	
	//*** PACKAGE ***
	
	public static final String RESIDE_PACKAGE_ENTITY_CLASS = RESIDE_FINAL_PACKAGE_ENTITY_CLASS + PACKAGE_INCLUDE;
	
	public static final String RESIDE_PACKAGE_DTO_CLASS = RESIDE_FINAL_PACKAGE_DTO_CLASS + PACKAGE_INCLUDE;
	public static final String RESIDE_PACKAGE_REQUEST_DTO_CLASS = RESIDE_FINAL_PACKAGE_REQUEST_DTO_CLASS + PACKAGE_INCLUDE;
	public static final String RESIDE_PACKAGE_RESPONSE_DTO_CLASS = RESIDE_FINAL_PACKAGE_RESPONSE_DTO_CLASS + PACKAGE_INCLUDE;
	public static final String RESIDE_PACKAGE_QUERY_REQUEST_DTO_CLASS = RESIDE_FINAL_PACKAGE_QUERY_REQUEST_DTO_CLASS + PACKAGE_INCLUDE;
	
	public static final String RESIDE_PACKAGE_REPOSITORY_CLASS = RESIDE_FINAL_PACKAGE_REPOSITORY_CLASS + PACKAGE_INCLUDE;
	public static final String RESIDE_PACKAGE_REPOSITORY_IMPL_CLASS = RESIDE_FINAL_PACKAGE_REPOSITORY_IMPL_CLASS + PACKAGE_INCLUDE;
	public static final String RESIDE_PACKAGE_SERVICE_CLASS = RESIDE_FINAL_PACKAGE_SERVICE_CLASS + PACKAGE_INCLUDE;
	public static final String RESIDE_PACKAGE_SERVICE_IMPL_CLASS = RESIDE_FINAL_PACKAGE_SERVICE_IMPL_CLASS + PACKAGE_INCLUDE;
	public static final String RESIDE_PACKAGE_CONTROLLER_CLASS = RESIDE_FINAL_PACKAGE_CONTROLLER_CLASS + PACKAGE_INCLUDE;
	
	public static final String RESIDE_PACKAGE_UTIL_CLASS = RESIDE_FINAL_PACKAGE_UTIL_CLASS + PACKAGE_INCLUDE;
	public static final String RESIDE_PACKAGE_SUPPORT_CLASS = RESIDE_FINAL_PACKAGE_SUPPORT_CLASS + PACKAGE_INCLUDE;
	
	public static final String RESIDE_PACKAGE_MAPPER_CLASS = RESIDE_FINAL_PACKAGE_MAPPER_CLASS + PACKAGE_INCLUDE;
	public static final String RESIDE_PACKAGE_MAPPER_IMPL_CLASS = RESIDE_FINAL_PACKAGE_MAPPER_IMPL_CLASS + PACKAGE_INCLUDE;
	
	public static final String RESIDE_PACKAGE_DATA_FACTORY_CLASS = RESIDE_FINAL_PACKAGE_DATA_FACTORY_CLASS + PACKAGE_INCLUDE;
	public static final String RESIDE_PACKAGE_DUMMY_CLASS = RESIDE_FINAL_PACKAGE_DUMMY_CLASS + PACKAGE_INCLUDE;
	public static final String RESIDE_PACKAGE_DUMMY_DATA_FACTORY_CLASS = RESIDE_FINAL_PACKAGE_DUMMY_DATA_FACTORY_CLASS + PACKAGE_INCLUDE;
	
	public static final String RESIDE_PACKAGE_CONSTANT_CLASS = RESIDE_FINAL_PACKAGE_CONSTANT_CLASS + PACKAGE_INCLUDE;
	public static final String RESIDE_PACKAGE_EXCEPTION_CLASS = RESIDE_FINAL_PACKAGE_EXCEPTION_CLASS + PACKAGE_INCLUDE;
	
	public static final String RESIDE_PACKAGE_ENUMERATION_CLASS = RESIDE_FINAL_PACKAGE_ENUMERATION_CLASS + PACKAGE_INCLUDE;
	
	public static final String RESIDE_PACKAGE_ANNOTATION_CLASS = RESIDE_FINAL_PACKAGE_ANNOTATION_CLASS + PACKAGE_INCLUDE;
	
}
